### ISSUE TITLE
Being able to add items to the shopping cart through the seatback passenger interface

### ISSUE THREAD

**Issue by kmysorekar** [kmysorekar/PO_Exercise#1]
[**Link to API Design**](http://)

**User Story**
As an airline passenger, I would like to use the _On-board_ or _seatback_ interface to select and add one or many items at a time to my Shopping Cart so that I can purchase them, all at once, quickly and conveniently.

**Tasks:**
* [ ] Being able to select and add a **single item** to the Cart
* [ ] Being able to select and add **multiple items** all at once to the Cart

**Acceptance Criteria/Definition of Done**   
* [ ] Validate through test/s that **adding _quantity_ 1 of a product to an empty shopping cart adds 1** _quantity_ of the select product   
* [ ] Validate through test/s that the `Add to Cart` button upon clicking **adds the selected item/s** immediately to the Cart - [**Use case # from Test Plan**](http://)
* [ ] Validate through test/s above works for **adding any items** from _General categories of Products_, _Services_, and _Media_ 
* [ ] Validate through test/s that “Add to Cart” button upon clicking takes passenger to their **Cart/Check out page**
* [ ] Validate through test/s that the **quantities in the Cart for items match precisely** with the quantity chosen for items during selection 
* [ ] Verify that a user gets **message** `Item/s added to the cart successfully` if there are no errors adding item/s to the cart and the items are added successfully 
* [ ] If a customer **adds the same item twice**, they should be reflected as separate entries in the Cart, see [issue #8](https://github.com/kmysorekar/PO_Exercise/issues/8). We **should not update** the count of existing item in the Cart 
* [ ] **Performance**: In case a long list of items are being added to the cart, verify through test/s that it doesn't take longer than 5 seconds to get all items added to the cart successfully  
* [ ] **Memory consumption**: In case a long list of items are being added to the cart, verify through test/s that the On-board device doesn't use excessive memory while adding many items to the cart  
* [ ] **Error Handling:**
       - If an item fails to get added to the cart because of connectivity issues (remember we are in a 
          flight), a **meaningful error message**, such as `Error occurred while adding <item> 
          to the cart, no item is added, please retry` should be displayed to the user
       - Existing items in the cart, if applicable, should be **unchanged**
       - The On-board device should be able to **recover from an error**
       - The On-board device **should not crash or hang**
       - The On-board should **remain on the same page/menu** as where the user clicked to add an item to add
