### ISSUE TITLE
Being able to add items to the shopping cart through the SkyMall App

### ISSUE THREAD

**Issue by kmysorekar** [kmysorekar/PO_Exercise#2]
**User Story**
As an airline passenger, I would like to use the SkyMall App on my mobile device to select and add one or many items, all at once, to my Shopping Cart so that I can purchase them, all at once, quickly and conveniently.

**Tasks:**
* [ ] Being able to select and add a **single item** at a time to the Cart
* [ ] Being able to select and add **multiple items** all at once to the Cart

**Acceptance Criteria/Definition of Done**
* [ ] Validate through test/s that **adding _quantity_ 1 of a product to an empty shopping cart adds 1** _quantity_ of the select product  
* [ ] Validate through test/s that the `Add to Cart` button upon clicking **adds the selected item/s immediately** to the Cart
* [ ] Validate through test/s above works for **adding any items** from _General categories of Products_, _Services_, and _Media_ 
* [ ] Validate through test/s that “Add to Cart” button upon clicking takes passenger to their **Cart/Check out Page**
* [ ] Validate through test/s that the **quantities** in the Cart for items match precisely with the quantity chosen for items during selection 
* [ ] Verify that a user gets **message** `Item/s added to the cart successfully` if there are no errors adding item/s to the cart and the items are added successfully 
* [ ] If a passenger **adds the same item more than once**, they should be reflected as separate entries in the Cart, see [issue #8](https://github.com/kmysorekar/PO_Exercise/issues/8). We **should not update** the quantity of existing item in the Cart 
* [ ] **Performance**: In case a long list of items are being added to the cart, verify through test/s that it doesn't take longer than 5 seconds to get all items added to the cart successfully  
* [ ] **Memory usage**: In case a long list of items are being added to the cart, verify through test/s that the App doesn't use excessive memory while adding many items to the cart  
* [ ] Validate above two items through test/s on low-end, high-end and mid range `Android` and `iOS` devices
* [ ] Validate above two items through test/s on `armv7` and `armv8` devices 
devices
* [ ] **Error Handling**:
       - If an item fails to get added to the cart because of connectivity issues (remember we are in a 
          flight), a **meaningful error message**, such as `Error occurred while adding <item> 
          to the cart, no item is added, please retry` should be displayed to the user
       - Existing items in the cart, if applicable, should be **unchanged**
       - The App should be able **recover from the error**
       - The App should **not crash or hang**
       - The App should **remain on the same page/menu** as where the user clicked to add an item to add
